### ISSUE TITLE
BUG: cloudライブラリのエラーによる不正動作 (Chew/JDA-Chewtilsに置き換え)

### ISSUE THREAD

**Issue by book000** [jaoafa/Javajaotan2#296]
cloudがアップデートされるまで利用不可。v2.9.0がダメ

```
[20:05:24] [JDA MainWS-ReadThread/ERROR]: One of the EventListeners had an uncaught exception
java.lang.NoSuchMethodError: 'net.dv8tion.jda.api.entities.TextChannel net.dv8tion.jda.api.events.message.MessageReceivedEvent.getTextChannel()'
	at cloud.commandframework.jda.JDACommandSender.of(JDACommandSender.java:74)
	at java.base/java.util.function.Function.lambda$compose$0(Function.java:68)
	at cloud.commandframework.jda.JDACommandListener.onMessageReceived(JDACommandListener.java:65)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:133)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

**Comment by book000** [comment]
cloudのアップデートを期待できないので（依存パッケージがまだv4系、alphaだからそれはそう）、別のライブラリに乗り換えるのが安全かもしれない

https://github.com/Chew/JDA-Chewtils
